/*
 */
package red_star_autos_software.forms;

import red_star_autos_software.classes.Log;
import red_star_autos_software.classes.User;
import red_star_autos_software.components.InvoiceTask;
import red_star_autos_software.handlers.FormHandler;
import red_star_autos_software.handlers.ViewHandler;
import red_star_autos_software.utils.Commands;
import red_star_autos_software.utils.DatabaseManager;
import red_star_autos_software.utils.StyleSetting;
import red_star_autos_software.views.InvoiceView;

/**
 *
 * @author joe
 */
public class UpdateInvoice extends javax.swing.JFrame {

    private final User USER;
    private final ViewHandler VHANDLER;
    private final javax.swing.JPanel PARENT;
    private final java.util.HashMap<String, Integer> jobs = new java.util.HashMap();
    private final java.util.HashMap<String, Integer> customers = new java.util.HashMap();
    private final java.util.HashMap<String, Integer> methods = new java.util.HashMap();
    private boolean addingCustomers = false;
    private float totalCost = 0.00f;
    private int selectedInvoice;
    
    /**
     * Update Invoice Window.
     * @param user The user that is logged in.
     * @param viewHandler The view handler from the dashboard.
     * @param panel The panel that the view is contained inside.
     **/
    public UpdateInvoice(User user, ViewHandler viewHandler, javax.swing.JPanel panel) {
        this.USER = user;
        this.VHANDLER = viewHandler;
        this.PARENT = panel;
        
        initComponents();
        
        // Custom Form Styling
        this.setLocation(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width / 2 - (this.getWidth() / 2), java.awt.Toolkit.getDefaultToolkit().getScreenSize().height / 2 - (this.getHeight() / 2));
        java.util.List<javax.swing.JButton> buttons = new java.util.ArrayList<>();
        buttons.add(btnGenerateInvoice);
        StyleSetting.applyButtonStyles(buttons, btnGenerateInvoice.getBackground(), btnGenerateInvoice.getBorder());
        
        // Get the customers and payment methods from the database.
        java.sql.ResultSet customerRes = DatabaseManager.Query("SELECT c.customer_id, c.customer_email, j.job_description, j.job_id FROM customers c JOIN jobs j ON c.customer_id = j.customer_id WHERE c.customer_id IN (SELECT customer_id FROM invoices)");
        java.sql.ResultSet paymentMethods = DatabaseManager.Query("SELECT method_id, method_name FROM payment_methods");
        try {
            // Add the customers and jobs to their HashMaps and insert the customers into the combobox.
            addingCustomers = true;
            while(customerRes.next()){
                comboCustomers.addItem(customerRes.getString("job_description") + " ("+customerRes.getString("customer_email")+")");
                jobs.put(customerRes.getString("job_description") + " ("+customerRes.getString("customer_email")+")", customerRes.getInt("job_id"));
                customers.put(customerRes.getString("job_description") + " ("+customerRes.getString("customer_email")+")", customerRes.getInt("customer_id"));
            }
            // Add the methods to their HashMap and insert the methods into the combobox.
            while(paymentMethods.next()){
                comboMethods.addItem(paymentMethods.getString("method_name"));
                methods.put(paymentMethods.getString("method_name"), paymentMethods.getInt("method_id"));
            }
        } catch (java.sql.SQLException e) {
            // Display an error message and Log the error.
            FormHandler.openMessageBox(new MessageBox("Error!", e.getMessage() + "\n\nContact System Administrator", javax.swing.JOptionPane.ERROR_MESSAGE));
            new Log(Commands.getDateTime(), e.getMessage(), USER.getId()).send();
        }
        
        DatabaseManager.Disconnect();
        comboCustomers.setSelectedIndex(-1);
        addingCustomers = false;
        this.setSize(this.getWidth(), 201);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGenerateInvoice = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboCustomers = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        panelCostOverview = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboMethods = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboFreq = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dateOfPay = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel6 = new javax.swing.JLabel();
        dateOfNext = new com.github.lgooddatepicker.components.DateTimePicker();
        totalCostLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(606, 48));
        jPanel1.setMinimumSize(new java.awt.Dimension(606, 48));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Red Star Auto Mechanics - Update Invoice");
        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLabel1.setFocusable(false);
        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() & ~java.awt.Font.BOLD, 26));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setInheritsPopupMenu(false);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_star_autos_software/assets/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnGenerateInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_star_autos_software/assets/icons/accept.png"))); // NOI18N
        btnGenerateInvoice.setText("Update");
        btnGenerateInvoice.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerateInvoice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        btnGenerateInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerateInvoice.setForeground(new java.awt.Color(102, 102, 102));
        btnGenerateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateInvoiceActionPerformed(evt);
            }
        });

        jLabel3.setText("Please select a invoice:");
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));

        comboCustomers.setEditable(true);
        comboCustomers.setBackground(new java.awt.Color(204, 204, 204));
        comboCustomers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        comboCustomers.setForeground(new java.awt.Color(102, 102, 102));
        comboCustomers.setToolTipText("");
        comboCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCustomersActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        panelCostOverview.setBackground(new java.awt.Color(204, 204, 204));
        panelCostOverview.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)), "Cost Overview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        panelCostOverview.setLayout(new java.awt.GridLayout(5, 1, 5, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_star_autos_software/assets/icons/creditcards.png"))); // NOI18N
        jLabel2.setText("Payment Method:");
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_star_autos_software/assets/icons/clock.png"))); // NOI18N
        jLabel4.setText("Payment Frequency:");
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));

        comboFreq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One-off", "Monthly", "Annually" }));
        comboFreq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFreqItemStateChanged(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_star_autos_software/assets/icons/calendar_view_day.png"))); // NOI18N
        jLabel5.setText("Date of Payment:");
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));

        dateOfPay.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_star_autos_software/assets/icons/calendar_view_week.png"))); // NOI18N
        jLabel6.setText("Next Billing:");
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));

        dateOfNext.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCostOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMethods, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateOfPay, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFreq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateOfNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCostOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMethods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        totalCostLabel.setText("Total Cost: £");
        totalCostLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalCostLabel.setToolTipText("Total cost of job.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(totalCostLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 774, Short.MAX_VALUE)
                        .addComponent(btnGenerateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboCustomers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(comboCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCostLabel))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateInvoiceActionPerformed
        // Get the local date of pay and date of next pay and set a java.sql.Timestamp for each.
        java.time.LocalDateTime dtp = dateOfPay.getDateTimeStrict();
        java.time.LocalDateTime dtnp = dateOfNext.getDateTimeStrict();
        java.sql.Timestamp datePay = java.sql.Timestamp.valueOf(dtp);
        java.sql.Timestamp dateNextPay = java.sql.Timestamp.valueOf(dtnp);
        
        String status = "Unpaid";
        if(comboFreq.getSelectedItem().equals("One-off")){
            status = "Paid";
        }
        
        // Values to insert into the database.
        Object[] values = new Object[]{
            jobs.get((String) comboCustomers.getSelectedItem()),
            customers.get((String) comboCustomers.getSelectedItem()),
            (int) totalCost,
            0,
            (String) comboFreq.getSelectedItem(),
            methods.get((String) comboMethods.getSelectedItem()),
            datePay,
            dateNextPay,
            status,
            selectedInvoice
        };
        
        if(DatabaseManager.Update("UPDATE invoices SET job_id = ?, customer_id = ?, invoice_owed = ?, invoice_paid = ?, invoice_freq = ?, invoice_method = ?, invoice_pay_date = ?, invoice_next_pay_date = ?, invoice_status = ? WHERE invoice_id = ?", values)){
            // If the database inserts successfully, repopulate the InvoiceView and dispose of the form.
            InvoiceView iv = new InvoiceView(USER, VHANDLER);
            VHANDLER.changeView(iv, PARENT);
            iv.populate();
            this.dispose();
            new Log(Commands.getDateTime(), "Successfully generated a new invoice.", USER.getId()).send();
        }else{
            new Log(Commands.getDateTime(), "Failed to generate a new invoice.", USER.getId()).send();
        }
        
    }//GEN-LAST:event_btnGenerateInvoiceActionPerformed

    private void comboCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCustomersActionPerformed
        // If adding customers is in progres do nothing.
        if(addingCustomers){
            this.setSize(this.getWidth(), 201);
            jPanel3.setVisible(false);
            return;
        }
        
        // Once the customers are added, if the user selects an index.
        if(comboCustomers.getSelectedItem() != null){
            // Update the forms size and styling
            this.setSize(this.getWidth(), 500);
            jPanel3.setVisible(true);
            
            // Reset the total cost value
            totalCost = 0.00f;
            
            // Get the tasks for the job from the tasks database.
            java.sql.ResultSet taskRes = DatabaseManager.Query("SELECT i.invoice_id, t.task_description, t.task_cost, c.customer_surname, c.customer_email FROM tasks t JOIN jobs j ON j.job_id = t.job_id JOIN invoices i ON i.job_id = j.job_id JOIN customers c ON j.customer_id = c.customer_id WHERE t.job_id = ?", new Object[]{
                jobs.get((String) comboCustomers.getSelectedItem())
            });
            
            try {
                while(taskRes.next()){
                    // Clear the previous panel.
                    if(panelCostOverview.getComponentCount() >= 5){
                        panelCostOverview.removeAll();
                    }
                    
                    // Add all the new tasks to the panel.
                    InvoiceTask it = new InvoiceTask(taskRes.getString("task_description"), taskRes.getFloat("task_cost"));
                    panelCostOverview.add(it);
                    it.setVisible(true);
                    panelCostOverview.repaint();
                    panelCostOverview.revalidate();
                    
                    // Increase the total cost accordingly.
                    totalCost += (float) taskRes.getFloat("task_cost");
                    selectedInvoice = taskRes.getInt("invoice_id");
                }
            } catch (java.sql.SQLException e) {
                // Display an error message and Log the error.
                FormHandler.openMessageBox(new MessageBox("Error!", e.getMessage() + "\n\nContact System Administrator", javax.swing.JOptionPane.ERROR_MESSAGE));
                new Log(Commands.getDateTime(), e.getMessage(), USER.getId()).send();
            }
            
            totalCostLabel.setText("Total Cost: £" + totalCost);
            dateOfPay.datePicker.setDateToToday();
            dateOfPay.timePicker.setTimeToNow();
            
            dateOfNext.setEnabled(false);
            java.time.LocalDate date = dateOfPay.getDatePicker().getDate();
            java.time.LocalTime time = dateOfPay.getTimePicker().getTime();
            dateOfNext.datePicker.setDate(date);
            dateOfNext.timePicker.setTime(time);
        }
        
        DatabaseManager.Disconnect();
    }//GEN-LAST:event_comboCustomersActionPerformed

    private void comboFreqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFreqItemStateChanged
        // Update the date of pay and date of next pay depening on the frequency of the payments.
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            if(comboFreq.getSelectedItem() == "One-off"){
                java.time.LocalDate date = dateOfPay.getDatePicker().getDate();
                java.time.LocalTime time = dateOfPay.getTimePicker().getTime();
                dateOfNext.datePicker.setDate(date);
                dateOfNext.timePicker.setTime(time);
            }
            
            if(comboFreq.getSelectedItem() == "Monthly"){
                java.time.LocalDate date = dateOfPay.getDatePicker().getDate();
                java.time.LocalDate nDate = date.plusMonths(1);
                dateOfNext.datePicker.setDate(nDate);
                dateOfNext.timePicker.setTime(java.time.LocalTime.MIN);
            }
            
            if(comboFreq.getSelectedItem() == "Annually"){
                java.time.LocalDate date = dateOfPay.getDatePicker().getDate();
                java.time.LocalDate nDate = date.plusYears(1);
                dateOfNext.datePicker.setDate(nDate);
                dateOfNext.timePicker.setTime(java.time.LocalTime.MIN);
            }
        }
    }//GEN-LAST:event_comboFreqItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateInvoice;
    private javax.swing.JComboBox<String> comboCustomers;
    private javax.swing.JComboBox<String> comboFreq;
    private javax.swing.JComboBox<String> comboMethods;
    private com.github.lgooddatepicker.components.DateTimePicker dateOfNext;
    private com.github.lgooddatepicker.components.DateTimePicker dateOfPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelCostOverview;
    private javax.swing.JLabel totalCostLabel;
    // End of variables declaration//GEN-END:variables
}
